// Compares csym against reference values and Jacobians generated by SymForce
// (tools/symforce_oracle/oracle.py -> tests/vectors/*.inc), and reports op counts side by side.

#include <cstdio>
#include <tuple>

#include "check.h"
#include "csym/csym.h"
#include "oracle_cases.h"
#include "vectors/arith.inc"
#include "vectors/atan2_eps.inc"
#include "vectors/barron_whiten.inc"
#include "vectors/barron_whiten_norm.inc"
#include "vectors/bicycle_factor.inc"
#include "vectors/pseudo_huber_whiten_norm.inc"
#include "vectors/robust_pose2_between.inc"
#include "vectors/robust_tire_factor.inc"
#include "vectors/exp_log.inc"
#include "vectors/inverse_trig.inc"
#include "vectors/nested.inc"
#include "vectors/norm_eps.inc"
#include "vectors/piecewise.inc"
#include "vectors/pose2_between.inc"
#include "vectors/pose2_between_group.inc"
#include "vectors/pose3_compose_group.inc"
#include "vectors/rot3_compose_group.inc"
#include "vectors/pose3_between.inc"
#include "vectors/pose3_inverse_act.inc"
#include "vectors/pose3_prior.inc"
#include "vectors/powers.inc"
#include "vectors/rot2_local.inc"
#include "vectors/rot3_act.inc"
#include "vectors/rot3_compose.inc"
#include "vectors/rot3_from_tangent.inc"
#include "vectors/rot3_local.inc"
#include "vectors/tire_fy.inc"
#include "vectors/trig.inc"

using namespace csym;

namespace {

template <class... Args>
std::tuple<Args...> unpack(const double* in) {
  std::tuple<Args...> t;
  std::size_t off = 0;
  std::apply([&](auto&... a) { ((a = storage<std::remove_cvref_t<decltype(a)>>::from(in + off),
                                 off += storage_dim<decltype(a)>), ...); }, t);
  return t;
}

template <class Fn, std::size_t... I, class... A>
auto jacobian_wrt(Wrt<I...>, const A&... a) {
  return Fn::template jacobian<I...>(a...);
}
template <class Fn, std::size_t... I, class... A>
auto linearize_wrt(Wrt<I...>, const A&... a) {
  return Fn::template linearize<I...>(a...);
}

// evaluate<I...>() with per-argument blocks must match the stacked jacobian(), both with every block
// requested and with the first one skipped (null).
template <class Fn, std::size_t... I, class J, class... A>
void check_blocks(Wrt<I...>, const J& stacked, const A&... a) {
  std::tuple<typename Fn::template Block<I>...> blocks;
  for (int skip_first = 0; skip_first < 2; ++skip_first) {
    std::apply([&](auto&... b) {
      int k = 0;
      auto ptr = [&](auto& block) { return (skip_first && k++ == 0) ? nullptr : &block; };
      (void)Fn::template evaluate<I...>(a..., ptr(b)...);
    }, blocks);
    std::size_t col = 0, k = 0;
    std::apply([&](const auto&... b) {
      auto cmp = [&](const auto& block) {
        const bool skipped = skip_first && k++ == 0;
        for (std::size_t i = 0; i < block.data.size(); ++i)
          if (!skipped) CHECK_CLOSE(block.data[i], stacked.data[col * block.rows + i], 1e-14, 1e-14);
        col += block.cols;
      };
      (cmp(b), ...);
    }, blocks);
  }
}

struct Tol {
  double rtol = 1e-9, atol = 1e-9;
};

template <auto F, class W, class... Args, class Samples>
void run(const char* name, const Samples& samples, int sf_value, int sf_jacobian, int sf_lin, Tol tol = {}) {
  using Fn = Function<F, Args...>;
  const int failures_before = check::failures;
  for (const auto& s : samples) {
    const auto args = unpack<Args...>(s.input.data());
    const auto r = std::apply([](const auto&... a) { return jacobian_wrt<Fn>(W{}, a...); }, args);
    std::array<double, Fn::output_dim> value{};
    storage<typename Fn::Output>::to(r.value, value.data());
    for (std::size_t i = 0; i < value.size(); ++i) CHECK_CLOSE(value[i], s.output[i], tol.rtol, tol.atol);
    CHECK(r.jacobian.data.size() == s.jacobian.size() || (s.jacobian.size() == 1 && r.jacobian.data.empty()));
    for (std::size_t i = 0; i < r.jacobian.data.size(); ++i)
      CHECK_CLOSE(r.jacobian.data[i], s.jacobian[i], tol.rtol, tol.atol);

    std::apply([&](const auto&... a) { check_blocks<Fn>(W{}, r.jacobian, a...); }, args);

    // linearize() must agree with jacobian(), and hessian/rhs must be JᵀJ / Jᵀr (vector residuals only).
    if constexpr (Fn::output_tangent_dim == Fn::output_dim) {
      const auto lin = std::apply([](const auto&... a) { return linearize_wrt<Fn>(W{}, a...); }, args);
      constexpr std::size_t n = decltype(lin.rhs)::rows, m = Fn::output_dim;
      for (std::size_t i = 0; i < m * n; ++i) CHECK_CLOSE(lin.jacobian.data[i], r.jacobian.data[i], 1e-12, 1e-12);
      for (std::size_t i = 0; i < n; ++i) {
        double rhs = 0;
        for (std::size_t k = 0; k < m; ++k) rhs += lin.jacobian(k, i) * lin.residual[k];
        CHECK_CLOSE(lin.rhs[i], rhs, 1e-10, 1e-10);
        for (std::size_t j = 0; j < n; ++j) {
          double h = 0;
          for (std::size_t k = 0; k < m; ++k) h += lin.jacobian(k, i) * lin.jacobian(k, j);
          CHECK_CLOSE(lin.hessian(i, j), i >= j ? h : 0.0, 1e-10, 1e-10);  // lower triangle
        }
      }
    }
  }
  std::size_t lin_ops = 0;
  if constexpr (Fn::output_tangent_dim == Fn::output_dim) lin_ops = Fn::template op_count<Mode::Linearization, W>;
  std::printf("%-18s %s  ops value %4zu (sf %4d)  jacobian %5zu (sf %5d)  linearization %5zu (sf %5d)\n", name,
              check::failures == failures_before ? "ok  " : "FAIL", Fn::template op_count<Mode::Value>, sf_value,
              Fn::template op_count<Mode::Jacobian, W>, sf_jacobian, lin_ops, sf_lin);
}

}  // namespace

#define RUN(name, W, ...)                                                                                 \
  run<oracle_cases::name, W, __VA_ARGS__>(#name, oracle::name::samples, oracle::name::sf_ops_value,       \
                                          oracle::name::sf_ops_jacobian, oracle::name::sf_ops_linearization)

int main() {
  using d = double;
  using V3 = Vector3<d>;
  using V4 = Vector<d, 4>;
  using R3 = Rot3<d>;
  using P2 = Pose2<d>;
  using P3 = Pose3<d>;
  using M66 = Matrix<d, 6, 6>;
  using W0 = Wrt<0>;
  using W01 = Wrt<0, 1>;
  using WTire = Wrt<0, 1, 2, 3, 5, 6, 7, 9>;
  using WBicycle = Wrt<0, 1, 2, 3>;
  using W013 = Wrt<0, 1, 3>;
  using WRobustTire = Wrt<0, 1, 2, 3, 5, 6, 7, 9, 12>;
  RUN(arith, W01, d, d);
  RUN(trig, W01, d, d);
  RUN(inverse_trig, W01, d, d);
  RUN(atan2_eps, W01, d, d, d);
  RUN(exp_log, W01, d, d);
  RUN(powers, W01, d, d);
  RUN(piecewise, W01, d, d);
  RUN(nested, W01, d, d, d);
  RUN(norm_eps, W0, V3, d);
  RUN(rot3_act, W01, R3, V3);
  RUN(rot3_compose, W01, R3, R3);
  RUN(rot3_local, W01, R3, R3, d);
  RUN(rot3_from_tangent, W0, V3, d);
  RUN(rot2_local, W01, Rot2<d>, Rot2<d>, d);
  RUN(pose2_between, W01, P2, P2, P2, Matrix33<d>, d);
  RUN(pose3_between, W01, P3, P3, P3, M66, d);
  RUN(pose3_prior, W0, P3, P3, M66, d);
  RUN(pose3_inverse_act, W01, P3, V3);
  RUN(rot3_compose_group, W01, R3, R3);
  RUN(pose3_compose_group, W01, P3, P3);
  RUN(pose2_between_group, W01, P2, P2);
  RUN(barron_whiten, W01, V3, d, d, d);
  RUN(barron_whiten_norm, W013, V3, d, d, d, d);
  RUN(pseudo_huber_whiten_norm, W01, Vector2<d>, d, d, d);
  RUN(tire_fy, WTire, d, d, d, d, d, d, d, d, d, d, d);
  RUN(robust_tire_factor, WRobustTire, d, d, d, d, d, d, d, d, d, d, d, d, d, d);
  RUN(robust_pose2_between, W01, P2, P2, P2, V3, d);
  RUN(bicycle_factor, WBicycle, P2, V3, P2, V3, Vector2<d>, V4, V4, V4, d, Vector<d, 6>, d);
  return check::report("oracle");
}
