# Multi-window layout configuration with Zenoh real-time data subscriptions
windows:
  # Instrument cluster window with gauges and telltales
  - name: "instrument_cluster"
    width: 1200
    height: 450
    background_color: "#555555"
    widgets:
      # Mercedes 190E Speedometer on the left - subscribes to vehicle speed
      - type: mercedes_190e_speedometer
        x: 350
        y: 15
        width: 250
        height: 250
        config:
          zenoh_key: "vehicle/speed_mps"  # Real-time speed data in m/s
          schema_type: "VehicleSpeed"

          odometer_value: 123456
          max_speed: 160
          shift_box_markers: [28, 54, 87]  # Boxes drawn on the arc to indicate points, in MPH.

          speed_expression: "mps_to_mph(speedMps)"
          odometer_expression: ""
      
      # Mercedes 190E Tachometer on the right - subscribes to engine RPM
      - type: mercedes_190e_tachometer
        x: 650
        y: 15
        width: 250
        height: 250
        config:
          zenoh_key: "vehicle/engine/rpm"  # Real-time RPM data
          max_rpm: 8000
          redline_rpm: 7000
          show_clock: true
      
      # Battery telltale indicator in top left - subscribes to battery warning
      - type: mercedes_190e_battery_telltale
        x: 50
        y: 400
        width: 30
        height: 30
        config:
          zenoh_key: "vehicle/telltales/battery_warning"
          schema_type: "BatteryWarning"  # Cap'n Proto schema type
          normal_color: "#333333"
          warning_color: "#FF0000"
          condition_expression: "batteryVoltage < 12.0"  # Uses batteryVoltage from BatteryWarning schema
      
      # Sparkline for engine data on top - subscribes to engine temperature
      - type: sparkline
        x: 950
        y: 15
        width: 200
        height: 40
        config:
          zenoh_key: "vehicle/engine/temperature_celsius"  # Real-time temperature data
          units: "Coolant (C)"
          min_value: -40
          max_value: 120
          line_color: "#FFA500"
          text_color: "#FFFFFF"
          font_family: "Futura"
          update_rate: 30

      # Cluster gauge for all gauges
      - type: mercedes_190e_cluster_gauge
        x: 50
        y: 15
        width: 250
        height: 250
        config:
          top_gauge:
            min_value: 0
            max_value: 100
            current_value: 50
          right_gauge:
            min_value: 0
            max_value: 100
            current_value: 75
          bottom_gauge:
            min_value: 0
            max_value: 80
            current_value: 40
          left_gauge:
            min_value: 0
            max_value: 40
            current_value: 20


  # Dedicated CarPlay window (no Zenoh subscription needed)
#  - name: "carplay"
#    width: 800
#    height: 600
#    widgets:
#      - type: carplay
#        x: 0
#        y: 0
#        width: 800
#        height: 600
#        config:
#          width_px: 800
#          height_px: 600
#          fps: 30
#          dpi: 160
#          format: 5
#          i_box_version: 2
#          phone_work_mode: 2
#          packet_max: 49152
#          box_name: "nodePlay"
#          night_mode: false
#          drive_type: "LHD"
#          media_delay: 300
#          audio_transfer_mode: false
#          wifi_type: "5Ghz"
#          mic_type: "OS"
#          phone_config:
#            car_play:
#              frame_interval: 5000
#            android_auto:
#              frame_interval: null
#
#          # Audio device buffer size (bytes) on the host.
#          audio_device_buffer_size: 16384