width_px: 800
height_px: 400
fps: 30
dpi: 160
format: 5
i_box_version: 2
phone_work_mode: 2
packet_max: 49152
box_name: "nodePlay"
night_mode: false
drive_type: "LHD"
media_delay: 300
audio_transfer_mode: false
wifi_type: "5Ghz"
mic_type: "OS"
phone_config:
  car_play:
    frame_interval: 5000
  android_auto:
    frame_interval: null

# Audio device buffer size (bytes) on the host.
audio_device_buffer_size: 16384

# Window layout configuration
window:
  width: 1024
  height: 768
  widgets:
    # Mercedes 190E Speedometer on the left
    - type: "speedometer"
      x: 50
      y: 100
      width: 300
      height: 300

    # Mercedes 190E Tachometer on the right
    - type: "tachometer"
      x: 450
      y: 100
      width: 300
      height: 300

    # Battery telltale indicator in top left
    - type: "battery_telltale"
      x: 50
      y: 50
      width: 30
      height: 30

    # Sparkline for engine data on top
    - type: "sparkline"
      x: 350
      y: 50
      width: 200
      height: 40

    # CarPlay widget in bottom area (optional - remove if not needed)
    - type: "carplay"
      x: 150
      y: 450
      width: 800
      height: 350