width_px: 800
height_px: 400
fps: 30
dpi: 160
format: 5
i_box_version: 2
phone_work_mode: 2
packet_max: 49152
box_name: "nodePlay"
night_mode: false
drive_type: "LHD"
media_delay: 300
audio_transfer_mode: false
wifi_type: "5Ghz"
mic_type: "OS"
phone_config:
  car_play:
    frame_interval: 5000
  android_auto:
    frame_interval: null

# Audio device buffer size (bytes) on the host.
audio_device_buffer_size: 16384