width_px: 800
height_px: 400
fps: 30
dpi: 160
format: 5
i_box_version: 2
phone_work_mode: 2
packet_max: 49152
box_name: "nodePlay"
night_mode: false
drive_type: "LHD"
media_delay: 300
audio_transfer_mode: false
wifi_type: "5Ghz"
mic_type: "OS"
phone_config:
  car_play:
    frame_interval: 5000
  android_auto:
    frame_interval: null

# Audio device buffer size (bytes) on the host.
audio_device_buffer_size: 16384

# Multi-window layout configuration
windows:
  # Instrument cluster window with gauges and telltales
  - name: "instrument_cluster"
    width: 800
    height: 450
    widgets:
      # Mercedes 190E Speedometer on the left
      - type: "speedometer"
        x: 50
        y: 75
        width: 250
        height: 250
      
      # Mercedes 190E Tachometer on the right
      - type: "tachometer" 
        x: 350
        y: 75
        width: 250
        height: 250
      
      # Battery telltale indicator in top left
      - type: "battery_telltale"
        x: 50
        y: 25
        width: 30
        height: 30
      
      # Sparkline for engine data on top
      - type: "sparkline"
        x: 300
        y: 25
        width: 200
        height: 40

  # Dedicated CarPlay window
  - name: "carplay"
    width: 800
    height: 600
    widgets:
      - type: "carplay"
        x: 0
        y: 0
        width: 800
        height: 600