#include "pcan_trc_parser/pcan_trc_parser.h"

#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <string>
#include <string_view>

#include <spdlog/spdlog.h>
#include <spdlog/fmt/ranges.h>

using namespace pcan_trc_parser;

namespace
{

// Checks report through the exit code rather than assert(). The project adds
// -DNDEBUG unconditionally, not just in Release, so every assert() in here was
// compiled away and the test passed no matter what the parser returned --
// verified by making one deliberately false and watching it still pass.
int failures = 0;

void expect(bool condition, const std::string& what)
{
    if (!condition)
    {
        SPDLOG_ERROR("FAIL: {}", what);
        ++failures;
    }
}

}  // namespace

// Embed sample.trc contents directly as a string literal
static constexpr const char kSampleTrc[] =
    ";$FILEVERSION=2.0\n"
    ";$STARTTIME=45941.6917846643\n"
    ";$COLUMNS=N,O,T,I,d,l,D\n"
    ";\n"
    ";   Start time: 10/11/2025 16:36:10.195.0\n"
    ";   Generated by PCAN-View v5.3.0.942\n"
    ";   Message   Time    Type ID     Rx/Tx\n"
    ";   Number    Offset  |    [hex]  |  Data Length\n"
    ";   |         [ms]    |    |      |  |  Data [hex] ...\n"
    ";   |         |       |    |      |  |  |\n"
    ";---+-- ------+------ +- --+----- +- +- +- +- -- -- -- -- -- -- --\n"
    "      1 4294967269.343 DT     0500 Rx 8  40 00 00 00 00 00 00 00 \n"
    "      2 4294967270.343 DT     0501 Rx 8  04 00 00 00 00 00 00 00 \n"
    "      3 4294967271.344 DT     0502 Rx 8  04 00 00 00 00 00 00 00 \n"
    "      4 4294967272.341 DT     0503 Rx 8  04 04 04 04 04 00 00 00 \n"
    "      5 4294967274.337 DT     0505 Rx 8  04 13 01 55 00 00 06 B5 \n"
    "      6 4294967279.267 DT     0500 Rx 8  00 00 00 00 00 00 00 00 \n"
    "      7 4294967280.245 DT     0501 Rx 8  00 00 00 00 00 00 00 00 \n"
    "      8 4294967281.245 DT     0502 Rx 8  00 00 00 00 00 00 00 00 \n"
    "      9 4294967282.234 DT     0503 Rx 8  00 12 12 12 12 12 13 12 \n"
    "     10 4294967283.248 DT     0504 Rx 8  00 00 00 00 00 00 00 00 \n";

int main()
{
    std::size_t count = 0;
    helpers::CanFrame first{};
    helpers::CanFrame last{};
    bool first_seen = false;

    auto on_frame = [&](const helpers::CanFrame& f)
    {
        if (!first_seen) {
            first = f;
            first_seen = true;
        }
        last = f;
        ++count;

        //const auto data = std::span<const uint8_t>(f.data.begin(), std::min(static_cast<std::size_t>(f.len), f.data.size()));

        SPDLOG_INFO("id: 0x{:08X}, len: {}, data: [{:02X}]",
            f.id,
            f.len,
            fmt::join(f.data_span(), ", ")
        );
        
        return true; // continue
    };

    // We keep the literal as a string_view, but pass the underlying C string to the API
    std::string_view sample_sv{kSampleTrc};
    const std::size_t delivered = parse_string(sample_sv.data(), on_frame);

    expect(delivered == 10, "parse_string reports 10 frames");
    expect(count == 10, "and the callback saw 10");

    expect(first.id == 0x0500, "first frame id");
    expect(first.len == 8, "first frame length");
    expect(first.data[0] == 0x40, "first frame leading byte");
    bool first_tail_zero = true;
    for (std::size_t i = 1; i < first.len; ++i)
    {
        first_tail_zero = first_tail_zero && first.data[i] == 0x00;
    }
    expect(first_tail_zero, "first frame is zero after the leading byte");

    expect(last.id == 0x0504, "last frame id");
    expect(last.len == 8, "last frame length");
    bool last_all_zero = true;
    for (std::size_t i = 0; i < last.len; ++i)
    {
        last_all_zero = last_all_zero && last.data[i] == 0x00;
    }
    expect(last_all_zero, "last frame is all zero");

    if (failures == 0)
    {
        SPDLOG_INFO("pcan trc parser tests passed");
        return EXIT_SUCCESS;
    }
    return EXIT_FAILURE;
}


