"""Generates reference test vectors for csym by running SymForce as a black box.

Each case below is a function written against SymForce's Python API. A C++ twin with the same name
lives in libs/csym/tests/oracle_test.cpp. For each case this script evaluates values and tangent-space
Jacobians at sampled points (via SymForce's own Python code generation), records the op count of
SymForce's generated C++, and writes libs/csym/tests/vectors/<case>.inc as constexpr arrays.

Nothing here is linked into or copied into csym; it only produces numbers.

Usage:  uv run oracle.py [output_dir]
"""

from __future__ import annotations

import dataclasses
import importlib.util
import pathlib
import re
import sys
import tempfile
import typing as T

import numpy as np

import symforce

symforce.set_epsilon_to_symbol()

import symforce.symbolic as sf  # noqa: E402
from symforce import codegen  # noqa: E402

import cases  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]


def storage(value: T.Any) -> list[float]:
    if isinstance(value, (int, float, np.floating)):
        return [float(value)]
    if isinstance(value, np.ndarray):
        return [float(v) for v in value.flatten(order="F")]
    if hasattr(value, "to_storage"):
        return [float(v) for v in value.to_storage()]
    return [float(v) for v in np.asarray(value).flatten(order="F")]


def load_function(path: str, name: str) -> T.Callable:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return getattr(module, name)


def op_count(case: cases.Case, mode: str, outdir: str) -> int:
    cg = codegen.Codegen.function(func=case.func, config=codegen.CppConfig(), name=case.name)
    if mode == "jacobian":
        cg = cg.with_jacobians(which_args=case.wrt, include_results=True)
    elif mode == "linearization":
        try:
            cg = cg.with_linearization(which_args=case.wrt)
        except ValueError:  # only defined for column-vector residuals
            return -1
    data = cg.generate_function(output_dir=f"{outdir}/cpp_{mode}", skip_directory_nesting=True)
    text = pathlib.Path(data.generated_files[0]).read_text()
    m = re.search(r"Total ops: (\d+)", text)
    return int(m.group(1)) if m else -1


def numeric_function(case: cases.Case, outdir: str) -> T.Callable:
    cg = codegen.Codegen.function(
        func=case.func, config=codegen.PythonConfig(), name=case.name
    ).with_jacobians(which_args=case.wrt, include_results=True)
    data = cg.generate_function(output_dir=f"{outdir}/py", skip_directory_nesting=True)
    py = next(p for p in data.generated_files if p.name == f"{cg.name}.py")
    return load_function(str(py), cg.name)


def fmt(values: T.Sequence[float]) -> str:
    return ", ".join(repr(float(v)) if np.isfinite(v) else "NAN" for v in values)


def generate(case: cases.Case, outdir: pathlib.Path, rng: np.random.Generator) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        fn = numeric_function(case, tmp)
        counts = {m: op_count(case, m, tmp) for m in ("value", "jacobian", "linearization")}

    samples = case.samples(rng)
    rows = []
    for args in samples:
        result = fn(*args)
        value, jacs = (result[0], result[1:]) if case.wrt else (result, [])
        if len(case.wrt) == 1 and not isinstance(result, tuple):
            value, jacs = result, []
        out = storage(value)
        def as_2d(j: T.Any) -> np.ndarray:
            a = np.asarray(j, dtype=float)
            # Rows are the output's tangent dimension (differs from storage for Lie-group outputs).
            return a if a.ndim == 2 else a.reshape(len(out), -1)

        J = np.hstack([as_2d(j) for j in jacs]) if jacs else np.zeros((len(out), 0))
        flat_in = [v for a in args for v in storage(a)]
        rows.append((flat_in, out, list(J.flatten(order="F"))))

    n_in, n_out, n_jac = len(rows[0][0]), len(rows[0][1]), len(rows[0][2])
    lines = [
        "// Generated by tools/symforce_oracle/oracle.py from SymForce "
        f"{symforce.__version__}. Do not edit.",
        f"// Case: {case.name} -- {case.doc}",
        "#pragma once",
        "#include <array>",
        f"namespace oracle::{case.name} {{",
        f"inline constexpr int sf_ops_value = {counts['value']};",
        f"inline constexpr int sf_ops_jacobian = {counts['jacobian']};",
        f"inline constexpr int sf_ops_linearization = {counts['linearization']};",
        f"inline constexpr std::size_t num_samples = {len(rows)}, input_dim = {n_in}, output_dim = {n_out}, jacobian_size = {n_jac};",
        "struct Sample {",
        f"  std::array<double, {n_in}> input;",
        f"  std::array<double, {n_out}> output;",
        f"  std::array<double, {max(n_jac, 1)}> jacobian;  // column-major, tangent columns stacked by argument",
        "};",
        f"inline constexpr std::array<Sample, {len(rows)}> samples = {{{{",
    ]
    for flat_in, out, jac in rows:
        lines.append(f"  {{{{{fmt(flat_in)}}}, {{{fmt(out)}}}, {{{fmt(jac) if jac else '0.0'}}}}},")
    lines += ["}};", f"}}  // namespace oracle::{case.name}", ""]
    (outdir / f"{case.name}.inc").write_text("\n".join(lines))
    print(f"{case.name:28s} samples={len(rows):3d} sf ops: value={counts['value']} "
          f"jacobian={counts['jacobian']} linearization={counts['linearization']}")


def main() -> None:
    outdir = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "libs" / "csym" / "tests" / "vectors"
    outdir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(12345)
    for case in cases.CASES:
        generate(case, outdir, rng)


if __name__ == "__main__":
    main()
