// SPDX-License-Identifier: GPL-3.0-or-later
// Known-answer tests for the AirPlay crypto primitives and SRP-6a.
//
// The stack cannot be exercised against a phone yet, so every primitive is
// pinned to a published vector where one exists:
//   X25519                 RFC 7748 sections 5.2 and 6.1
//   Ed25519                RFC 8032 section 7.1
//   ChaCha20-Poly1305      RFC 8439 section 2.8.2
//   AES-128-CTR            NIST SP 800-38A section F.5.1
//   SHA-1 / SHA-256        FIPS 180-4 "abc"
//   HKDF-SHA512            RFC 5869 test case 1 inputs, SHA-512 instantiation
//   SRP-6a (SHA-512/3072)  no published vector exists, so the expected values
//                          were generated by an independent Python port of
//                          LIVI's srp.ts and are pinned here.
#include "airplay/crypto.h"
#include "airplay/srp.h"

#include <spdlog/spdlog.h>

#include <cstdlib>
#include <string>

namespace
{

using airplay::crypto::Bytes;

int failures = 0;

void expect(bool condition, const char* what)
{
    if (!condition)
    {
        SPDLOG_ERROR("FAIL: {}", what);
        ++failures;
    }
}

int hexDigit(char c)
{
    if (c >= '0' && c <= '9')
    {
        return c - '0';
    }
    if (c >= 'a' && c <= 'f')
    {
        return c - 'a' + 10;
    }
    if (c >= 'A' && c <= 'F')
    {
        return c - 'A' + 10;
    }
    return -1;
}

Bytes fromHex(std::string_view hex)
{
    Bytes out;
    out.reserve(hex.size() / 2);
    for (size_t i = 0; i + 1 < hex.size(); i += 2)
    {
        out.push_back(static_cast<uint8_t>((hexDigit(hex[i]) << 4) | hexDigit(hex[i + 1])));
    }
    return out;
}

std::string toHex(const Bytes& bytes)
{
    static constexpr char kHex[] = "0123456789abcdef";
    std::string out;
    out.reserve(bytes.size() * 2);
    for (uint8_t b : bytes)
    {
        out.push_back(kHex[b >> 4]);
        out.push_back(kHex[b & 0x0f]);
    }
    return out;
}

Bytes toBytes(std::string_view text)
{
    return Bytes(text.begin(), text.end());
}

// The negative tests deliberately trip the ERROR logging; silence it so a
// passing run stays quiet.
struct QuietLogs
{
    QuietLogs() { spdlog::set_level(spdlog::level::off); }
    ~QuietLogs() { spdlog::set_level(spdlog::level::info); }
};

void testHashes()
{
    using airplay::crypto::sha1;
    using airplay::crypto::sha256;
    using airplay::crypto::sha512;

    expect(toHex(sha1({toBytes("abc")})) == "a9993e364706816aba3e25717850c26c9cd0d89d", "SHA-1 KAT (abc)");
    expect(toHex(sha1({})) == "da39a3ee5e6b4b0d3255bfef95601890afd80709", "SHA-1 KAT (empty)");
    expect(toHex(sha256({toBytes("abc")})) == "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
           "SHA-256 KAT (abc)");
    expect(toHex(sha512({toBytes("abc")})) ==
               "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a"
               "2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f",
           "SHA-512 KAT (abc)");

    // Multi-part update must equal the concatenated input.
    expect(sha256({toBytes("a"), toBytes("b"), toBytes("c")}) == sha256({toBytes("abc")}), "SHA-256 multi-part");
    expect(sha1({toBytes("ab"), {}, toBytes("c")}) == sha1({toBytes("abc")}), "SHA-1 multi-part with empty part");
}

void testHkdf()
{
    using airplay::crypto::hkdfSha512;

    // RFC 5869 test case 1 inputs, SHA-512 instantiation.
    const Bytes ikm(22, 0x0b);
    const Bytes salt_bytes = fromHex("000102030405060708090a0b0c");
    const Bytes info_bytes = fromHex("f0f1f2f3f4f5f6f7f8f9");
    const std::string salt(salt_bytes.begin(), salt_bytes.end());
    const std::string info(info_bytes.begin(), info_bytes.end());
    expect(toHex(hkdfSha512(ikm, salt, info, 42)) ==
               "832390086cda71fb47625bb5ceb168e4c8e26a1a16ed34d9fc7fe92c1481579338da362cb8d9f925d7cb",
           "HKDF-SHA512 KAT (RFC 5869 TC1 inputs)");

    // Empty salt and info: RFC 5869 says the salt defaults to HashLen zeros.
    expect(toHex(hkdfSha512(ikm, "", "", 64)) ==
               "f5fa02b18298a72a8c23898a8703472c6eb179dc204c03425c970e3b164bf90f"
               "ff22d04836d0e2343bacc4e7cb6045faaa698e0e3b3eb91331306def1db8319e",
           "HKDF-SHA512 KAT (empty salt/info)");

    Bytes counting(32);
    for (size_t i = 0; i < counting.size(); ++i)
    {
        counting[i] = static_cast<uint8_t>(i);
    }

    // A pair-setup shaped derivation.
    expect(toHex(hkdfSha512(counting, "Pair-Setup-Encrypt-Salt", "Pair-Setup-Encrypt-Info", 32)) ==
               "52890146745a52e57b82b859a7a3679c7f3d40bb295b055a0c8fa8af92a3746d",
           "HKDF-SHA512 KAT (Pair-Setup-Encrypt)");

    // More than two blocks, to cover the expand loop's counter.
    expect(toHex(hkdfSha512(counting, "Control-Salt", "Control-Write-Encryption-Key", 129)) ==
               "c3ca130c7033dbe5e7ff7f91d117ead869bac476994c7a48ca170c111136ed96"
               "5d427cc71e4fd005cd72280a041be0793d0c63dbe86ff841e5824241f432afd2"
               "651e30fd4051305707355766035bf463098dcc1da434d557417d2446545b18fd"
               "cc8d17b9039373372851abadc296d62b6c40215e94ed32e15581e8f99caaf348"
               "2b",
           "HKDF-SHA512 KAT (129-byte output, 3 expand blocks)");

    const QuietLogs quiet;
    expect(hkdfSha512(ikm, "salt", "info", 0).empty(), "HKDF rejects a zero-length output");
}

void testX25519()
{
    using airplay::crypto::x25519Generate;
    using airplay::crypto::x25519Shared;

    // RFC 7748 section 5.2, vector 1.
    expect(toHex(x25519Shared(fromHex("a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4"),
                              fromHex("e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c"))) ==
               "c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552",
           "X25519 KAT (RFC 7748 5.2 vector 1)");

    // RFC 7748 section 5.2, vector 2.
    expect(toHex(x25519Shared(fromHex("4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d"),
                              fromHex("e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493"))) ==
               "95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957",
           "X25519 KAT (RFC 7748 5.2 vector 2)");

    // RFC 7748 section 6.1 Diffie-Hellman, from both sides.
    const Bytes alice_private = fromHex("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a");
    const Bytes alice_public = fromHex("8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a");
    const Bytes bob_private = fromHex("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb");
    const Bytes bob_public = fromHex("de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f");
    const char* expected = "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742";
    expect(toHex(x25519Shared(alice_private, bob_public)) == expected, "X25519 KAT (RFC 7748 6.1, alice side)");
    expect(toHex(x25519Shared(bob_private, alice_public)) == expected, "X25519 KAT (RFC 7748 6.1, bob side)");

    // Freshly generated pairs must agree.
    const auto a = x25519Generate();
    const auto b = x25519Generate();
    expect(a.private_key.size() == 32 && a.public_key.size() == 32, "X25519 generate sizes");
    expect(a.public_key != b.public_key, "X25519 generate is not deterministic");
    expect(!x25519Shared(a.private_key, b.public_key).empty() &&
               x25519Shared(a.private_key, b.public_key) == x25519Shared(b.private_key, a.public_key),
           "X25519 agreement between fresh pairs");

    const QuietLogs quiet;
    expect(x25519Shared({}, bob_public).empty(), "X25519 rejects an empty private key");
    expect(x25519Shared(alice_private, fromHex("00")).empty(), "X25519 rejects a short peer key");
    // An all-zero peer key produces an all-zero secret, which OpenSSL rejects.
    expect(x25519Shared(alice_private, Bytes(32, 0)).empty(), "X25519 rejects a low-order peer key");
}

void testEd25519()
{
    using airplay::crypto::ed25519FromSeed;
    using airplay::crypto::ed25519Generate;
    using airplay::crypto::ed25519Sign;
    using airplay::crypto::ed25519Verify;

    struct Vector
    {
        const char* seed;
        const char* public_key;
        const char* message;
        const char* signature;
    };

    // RFC 8032 section 7.1, TEST 1..3.
    const Vector vectors[] = {
        {"9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
         "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a", "",
         "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0"
         "595bbe24655141438e7a100b"},
        {"4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
         "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c", "72",
         "92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb69da085ac1e43e15996e458f3613d0f11d8c387b2eae"
         "b4302aeeb00d291612bb0c00"},
        {"c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7",
         "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025", "af82",
         "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac18ff9b538d16f290ae67f760984dc6594a7c15e9"
         "716ed28dc027beceea1ec40a"},
    };

    for (const auto& v : vectors)
    {
        const Bytes seed = fromHex(v.seed);
        const Bytes message = fromHex(v.message);
        const auto pair = ed25519FromSeed(seed);
        expect(toHex(pair.public_key) == v.public_key, "Ed25519 KAT public key (RFC 8032 7.1)");
        expect(pair.private_key == seed, "Ed25519 seed round trip");
        expect(toHex(ed25519Sign(seed, message)) == v.signature, "Ed25519 KAT signature (RFC 8032 7.1)");
        expect(ed25519Verify(pair.public_key, message, fromHex(v.signature)), "Ed25519 KAT verify (RFC 8032 7.1)");
    }

    // Tampering must be caught.
    const Bytes seed = fromHex(vectors[2].seed);
    const auto pair = ed25519FromSeed(seed);
    Bytes signature = fromHex(vectors[2].signature);
    Bytes message = fromHex(vectors[2].message);
    signature[0] ^= 0x01;
    const QuietLogs quiet;
    expect(!ed25519Verify(pair.public_key, message, signature), "Ed25519 rejects a mangled signature");
    signature[0] ^= 0x01;
    message[0] ^= 0x01;
    expect(!ed25519Verify(pair.public_key, message, signature), "Ed25519 rejects a mangled message");
    expect(!ed25519Verify(fromHex(vectors[1].public_key), fromHex(vectors[2].message), signature),
           "Ed25519 rejects the wrong public key");
    expect(!ed25519Verify(pair.public_key, message, {}), "Ed25519 rejects an empty signature");
    expect(ed25519FromSeed({}).public_key.empty(), "Ed25519 rejects an empty seed");

    const auto generated = ed25519Generate();
    expect(generated.private_key.size() == 32 && generated.public_key.size() == 32, "Ed25519 generate sizes");
    expect(ed25519FromSeed(generated.private_key).public_key == generated.public_key,
           "Ed25519 generated seed rebuilds the same public key");
}

void testChacha()
{
    using airplay::crypto::chachaOpen;
    using airplay::crypto::chachaSeal;
    using airplay::crypto::nonce64;
    using airplay::crypto::nonceLabel;

    // RFC 8439 section 2.8.2.
    const Bytes key = fromHex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
    const Bytes nonce = fromHex("070000004041424344454647");
    const Bytes aad = fromHex("50515253c0c1c2c3c4c5c6c7");
    const Bytes plaintext = toBytes(
        "Ladies and Gentlemen of the class of '99: If I could offer you only one tip for the future, sunscreen would "
        "be it.");
    const std::string expected =
        "d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d63dbea45e8ca9671282fafb69da92728b1a71de0a9e"
        "060b2905d6a5b67ecd3b3692ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc3ff4def08e4b7a9de576"
        "d26586cec64b6116"
        "1ae10b594f09e26a7e902ecbd0600691";

    const Bytes sealed = chachaSeal(key, nonce, plaintext, aad);
    expect(toHex(sealed) == expected, "ChaCha20-Poly1305 KAT (RFC 8439 2.8.2)");

    const auto opened = chachaOpen(key, nonce, sealed, aad);
    expect(opened.has_value() && *opened == plaintext, "ChaCha20-Poly1305 open round trip");

    // Empty plaintext still produces a bare tag that authenticates.
    const Bytes empty_sealed = chachaSeal(key, nonce, {}, aad);
    expect(empty_sealed.size() == 16, "ChaCha20-Poly1305 seals an empty plaintext to a bare tag");
    const auto empty_opened = chachaOpen(key, nonce, empty_sealed, aad);
    expect(empty_opened.has_value() && empty_opened->empty(), "ChaCha20-Poly1305 opens a bare tag");

    // No AAD at all (the default argument path used by the event channel).
    const Bytes no_aad = chachaSeal(key, nonce, plaintext);
    const auto no_aad_open = chachaOpen(key, nonce, no_aad);
    expect(no_aad != sealed, "ChaCha20-Poly1305 AAD changes the tag");
    expect(no_aad_open.has_value() && *no_aad_open == plaintext, "ChaCha20-Poly1305 round trip without AAD");

    const QuietLogs quiet;
    Bytes tampered = sealed;
    tampered.back() ^= 0x01;
    expect(!chachaOpen(key, nonce, tampered, aad).has_value(), "ChaCha20-Poly1305 rejects a mangled tag");
    tampered = sealed;
    tampered[0] ^= 0x01;
    expect(!chachaOpen(key, nonce, tampered, aad).has_value(), "ChaCha20-Poly1305 rejects mangled ciphertext");
    expect(!chachaOpen(key, nonce, sealed, {}).has_value(), "ChaCha20-Poly1305 rejects missing AAD");
    expect(!chachaOpen(key, nonce64(1), sealed, aad).has_value(), "ChaCha20-Poly1305 rejects the wrong nonce");
    expect(!chachaOpen(key, nonce, fromHex("0011"), aad).has_value(), "ChaCha20-Poly1305 rejects a runt input");
    expect(chachaSeal(fromHex("00"), nonce, plaintext, aad).empty(), "ChaCha20-Poly1305 rejects a short key");
    expect(chachaSeal(key, fromHex("00"), plaintext, aad).empty(), "ChaCha20-Poly1305 rejects a short nonce");
}

void testNonces()
{
    using airplay::crypto::nonce64;
    using airplay::crypto::nonceLabel;

    expect(toHex(nonce64(0)) == "000000000000000000000000", "nonce64(0)");
    expect(toHex(nonce64(1)) == "000000000100000000000000", "nonce64(1) is little-endian at offset 4");
    expect(toHex(nonce64(0x0102030405060708ull)) == "000000000807060504030201", "nonce64 byte order");
    expect(toHex(nonce64(0xffffffffffffffffull)) == "00000000ffffffffffffffff", "nonce64 saturated");

    expect(toHex(nonceLabel("PV-Msg02")) == "00000000" + toHex(toBytes("PV-Msg02")),
           "nonceLabel right-aligns the label");
    expect(toHex(nonceLabel("PS-Msg05")) == "0000000050532d4d73673035", "nonceLabel KAT (PS-Msg05)");
    expect(toHex(nonceLabel("")) == "000000000000000000000000", "nonceLabel with an empty label");
}

void testAesCtr()
{
    using airplay::crypto::aesCtr128;

    // NIST SP 800-38A section F.5.1, CTR-AES128.Encrypt.
    const Bytes key = fromHex("2b7e151628aed2a6abf7158809cf4f3c");
    const Bytes iv = fromHex("f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff");
    const Bytes plaintext = fromHex(
        "6bc1bee22e409f96e93d7e117393172a"
        "ae2d8a571e03ac9c9eb76fac45af8e51"
        "30c81c46a35ce411e5fbc1191a0a52ef"
        "f69f2445df4f9b17ad2b417be66c3710");
    const std::string expected =
        "874d6191b620e3261bef6864990db6ce"
        "9806f66b7970fdff8617187bb9fffdff"
        "5ae4df3edbd5d35e5b4f09020db03eab"
        "1e031dda2fbe03d1792170a0f3009cee";

    const Bytes ciphertext = aesCtr128(key, iv, plaintext);
    expect(toHex(ciphertext) == expected, "AES-128-CTR KAT (NIST SP 800-38A F.5.1)");
    expect(aesCtr128(key, iv, ciphertext) == plaintext, "AES-128-CTR is its own inverse");

    // A partial trailing block must not be padded out.
    const Bytes partial(fromHex("00112233445566"));
    expect(aesCtr128(key, iv, partial).size() == partial.size(), "AES-128-CTR keeps a partial block's length");
    expect(aesCtr128(key, iv, {}).empty(), "AES-128-CTR on an empty input");

    const QuietLogs quiet;
    expect(aesCtr128(fromHex("0011"), iv, plaintext).empty(), "AES-128-CTR rejects a short key");
    expect(aesCtr128(key, fromHex("0011"), plaintext).empty(), "AES-128-CTR rejects a short IV");
}

void testRandom()
{
    using airplay::crypto::randomBytes;
    using airplay::crypto::randomId;

    const Bytes a = randomBytes(32);
    const Bytes b = randomBytes(32);
    expect(a.size() == 32 && b.size() == 32, "randomBytes length");
    expect(a != b, "randomBytes is not constant");
    expect(randomBytes(0).empty(), "randomBytes(0)");

    const std::string id = randomId();
    expect(id.size() == 17, "randomId is a 6-byte MAC-style identifier");
    bool well_formed = true;
    for (size_t i = 0; i < id.size(); ++i)
    {
        const bool separator = (i % 3) == 2;
        well_formed &= separator ? (id[i] == ':') : (hexDigit(id[i]) >= 0);
    }
    expect(well_formed, "randomId is colon-separated hex");
    expect(id.find_first_of("abcdef") == std::string::npos, "randomId is uppercase");
}

void testSrp()
{
    using airplay::srp::Client;
    using airplay::srp::Server;

    // No published SRP-6a vector exists for the SHA-512/3072-bit HomeKit
    // variant, so these were generated with an independent Python port of
    // LIVI's srp.ts (same group, same padding rules, same hash ordering).
    const Bytes salt = fromHex("101112131415161718191a1b1c1d1e1f");
    const Bytes private_b = fromHex("404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f");
    const Bytes private_a = fromHex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
    const std::string password = "1234-567";

    const std::string expected_b =
        "c1d28af68fae6e7ecf1d6d8383c0c646b516170b8342ec5a3afa22d023678bc7"
        "4459f5e617d2fe93379ea821525db2c40d29c73c0eb7c89336481c8ee565773c"
        "a39e68707d71761d039ce19c2ae87434335f11df40aa78e49cd9aba5251d4dc1"
        "66077f52c967d201af15cb99880107d97763180f65c1bd36cfe71435ff4256c0"
        "23a65caf9cd319e46f2bd9cebc838858a4054430f5880a0e8bd66481ce6478c6"
        "13f176be54db986d6ed4ab21e347d68937054c12647d1182e1b3c0dd11771a8a"
        "12b140deb56ea17329a46459c64bbdd2fe69c055391469dd5ee839a70a5c79c2"
        "832aff0b8a0172e0da545668c2e69865388e7ef1313b9c56a690af0f4f5190d8"
        "08c90f4bb797bbad6b27f6f232ff1355f16510b618f92060c503731b4c9d6188"
        "8c725d097d7ee76d8e8f0d64c5a905b052691ecfde7510dc2fc202ea1c1a48f6"
        "a64c059ff37e512fc4e953f1d3931eddde534b9d7761a496f766cd23fa6c639a"
        "0d143c5dddad13c2c8a4dd285226bd7b2f4ee116af7db3ab12a1ef567283b4a2";
    const std::string expected_a =
        "ccca32f3b34e28414ef721be45fd36a3cff2fda6d28237d3b5769850cc4ac93c"
        "a651055ef059fea8397473b9e67955ef0c46f2f713bd46ba432438d2f4873bd0"
        "02ead443e9c29991be7d619bd3ed87848b8e90936b352c1838e8853b5dbba7d0"
        "da2647d6a234f214b6bd2bd9461c1251ff586c77cd87bc6b2ce44f9989d00254"
        "e08be805af295422e1bf6a419431b70371190ae548d0b7af7428cef36b31a341"
        "26d6a425db475851d4f9a805a8ea90922d3e1aa013ae01a648f76e0f44a43eb0"
        "f4ea693ed5c6443a73c574f2fddbbe88153aa70a70ab037fee3c868d66a5b901"
        "daf09d924c69fcf31730f12d62cf3c0d312f01e8cbc0de1c773b242179fcbe49"
        "72e52aa19c881cc3609235a800b49354dcd2a1e9cb82286d67de266bc6c1d842"
        "1d8fe176778411d43e318a1d51d06b1ef8fdbff209f6476246e0dc9b10caee6c"
        "27bdb80d3a224be996952de33d7dd248cea3e94487dcc96626b7806e4941495c"
        "29aa3deab6e854c03f7520cd5d0f446818914b06d41a5a68b42619fedf09dcd3";
    const std::string expected_verifier =
        "c04ced91104cce248f801e34fbc69aa335480193828610869411a9bf567f4894"
        "37f54690a4d5a024942ec037963cc5abaea571a13fa626eabb77a719fca8daa2"
        "a4b022c642ab4752569a7ee94566ed25518f6caf361fde99ae30f5baceb0399a"
        "c5de87986ef3f75e897efb0235178ec5916f68d8e9e183e6c4bc2600331b7ef8"
        "727507fe702d95759e8faa88f5b488932adf6fa21453e8d68ef9be2c13290c29"
        "6d9ebe5a437099e6cd367dcea46f7ebcf83990c7a8233d236f249743beec07d4"
        "9a42e72e25dc21bd31d1fd0bc396159b2f1e81e6808921ce968c641be2b63517"
        "89fab74ef64a4118831e0359833c817d8ed3e7bfd976107d17286b08497ec5cf"
        "ae798c539412c9128bd3599a4ef7c3c1f136f7fd333842e2ea48beec421e36fc"
        "6e59c0d5f20a495a3966b3061455ddf752ee71120ad7d8a40d3dbfaa26cb6bea"
        "0e939ad76a4fa9df635f7072b6e979fa599bb30ddffd1cd5e117b1db5f7569db"
        "e19f742b209a4513d5c7ad99a9944e35ee9f0b3f093837477accf8087b3fcbe5";
    const std::string expected_k =
        "e61ca4e44886b7ea85e708773635f0855f86905a13ec474a6c6ea61fcbdc0342"
        "7f8ae0c5932c7acff44bdad218bd318cce5f7b37777d27ff1ff6966c3f8df0eb";
    const std::string expected_m1 =
        "8de6b8661151a5b57d48203f768e93ced03141f250248154240695ff3e579fce"
        "d7167bcfccfdc9d2971511c4e92083a9ef3940ad71e9abda677351c133fda423";
    const std::string expected_m2 =
        "46b99807b4a64c3be7a32d861f044e4cb9f76f713b3dfb6dac393e8e170046bf"
        "bece0b2cfa413c44b9a6f344eef08bbb2464e6649735072e36179f0e19cdd6b9";

    const Server server(airplay::srp::kPairSetupUsername, password, salt, private_b);
    expect(server.valid(), "SRP server construction");
    expect(server.salt() == salt, "SRP server keeps the salt");
    expect(server.publicB().size() == airplay::srp::kModulusBytes, "SRP B is left-padded to 384 bytes");
    expect(toHex(server.publicB()) == expected_b, "SRP KAT server public B");
    expect(toHex(server.verifier()) == expected_verifier, "SRP KAT verifier v");

    const auto verifier = airplay::srp::computeVerifier(airplay::srp::kPairSetupUsername, password, salt);
    expect(verifier.has_value() && toHex(*verifier) == expected_verifier, "SRP KAT computeVerifier");

    Client client(airplay::srp::kPairSetupUsername, password, private_a);
    expect(client.valid(), "SRP client construction");
    expect(toHex(client.publicA()) == expected_a, "SRP KAT client public A");

    const auto proof = client.computeProof(server.salt(), server.publicB());
    expect(proof.ok, "SRP client proof computed");
    expect(toHex(proof.session_key) == expected_k, "SRP KAT session key K");
    expect(toHex(proof.client_proof) == expected_m1, "SRP KAT client proof M1");

    const auto result = server.verify(client.publicA(), proof.client_proof);
    expect(result.ok, "SRP server accepts the client proof");
    expect(toHex(result.session_key) == expected_k, "SRP server derives the same K");
    expect(toHex(result.server_proof) == expected_m2, "SRP KAT server proof M2");
    expect(client.checkServerProof(result.server_proof), "SRP client accepts the server proof");

    // Full random exchange, ten times, to shake out padding-dependent paths.
    bool all_ok = true;
    for (int i = 0; i < 10; ++i)
    {
        const Server random_server(airplay::srp::kPairSetupUsername, "3939");
        Client random_client(airplay::srp::kPairSetupUsername, "3939");
        const auto client_proof = random_client.computeProof(random_server.salt(), random_server.publicB());
        const auto server_result = random_server.verify(random_client.publicA(), client_proof.client_proof);
        all_ok &= client_proof.ok && server_result.ok && server_result.session_key == client_proof.session_key &&
                  random_client.checkServerProof(server_result.server_proof);
    }
    expect(all_ok, "SRP random round trip x10");

    const QuietLogs quiet;

    // Wrong password: the proofs must not line up.
    {
        const Server strict(airplay::srp::kPairSetupUsername, "1234-567", salt, private_b);
        Client wrong(airplay::srp::kPairSetupUsername, "7654-321", private_a);
        const auto wrong_proof = wrong.computeProof(strict.salt(), strict.publicB());
        expect(wrong_proof.ok, "SRP client still produces a proof with the wrong password");
        expect(!strict.verify(wrong.publicA(), wrong_proof.client_proof).ok, "SRP rejects the wrong password");
    }

    // Wrong username with the right password.
    {
        Client wrong("Pair-Verify", password, private_a);
        const auto wrong_proof = wrong.computeProof(server.salt(), server.publicB());
        expect(!server.verify(wrong.publicA(), wrong_proof.client_proof).ok, "SRP rejects the wrong username");
    }

    // A ≡ 0 (mod N) must be refused outright.
    expect(!server.verify(Bytes(airplay::srp::kModulusBytes, 0), proof.client_proof).ok, "SRP rejects A = 0");
    expect(!server.verify(fromHex(airplay::srp::kModulusHex), proof.client_proof).ok, "SRP rejects A = N");

    // A mangled M1 must be refused.
    Bytes bad_m1 = proof.client_proof;
    bad_m1[0] ^= 0x01;
    expect(!server.verify(client.publicA(), bad_m1).ok, "SRP rejects a mangled M1");
    expect(!server.verify(client.publicA(), {}).ok, "SRP rejects an empty M1");
    expect(!client.checkServerProof({}), "SRP client rejects an empty M2");

    // The group really is the RFC 5054 3072-bit prime.
    expect(fromHex(airplay::srp::kModulusHex).size() == airplay::srp::kModulusBytes, "SRP modulus is 3072 bits");
}

}  // namespace

int main()
{
    spdlog::set_level(spdlog::level::info);

    testHashes();
    testHkdf();
    testX25519();
    testEd25519();
    testChacha();
    testNonces();
    testAesCtr();
    testRandom();
    testSrp();

    if (failures == 0)
    {
        SPDLOG_INFO("crypto tests passed");
        return EXIT_SUCCESS;
    }
    SPDLOG_ERROR("{} crypto test(s) failed", failures);
    return EXIT_FAILURE;
}
