#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generates the synthetic test DBCs under tests/dbcs/ and the cantools goldens
# for them, as an embedded C++ header.
#
# Why synthetic rather than the DBCs the product ships: pinning values from a
# real DBC couples the test suite to files that evolve for product reasons, so
# adding a signal to Motec_M1_Rev3.dbc would break a parser test. These inputs
# never change, so their goldens never need regenerating.
#
# That trade is only sound if the synthetic corpus covers the layout space
# exhaustively -- a round-trip bug in a real DBC has to be impossible unless
# the corpus would also have caught it. So the sweep below is *generated* over
# every combination of byte order, signedness, length and bit alignment rather
# than hand-picked, and the counts it prints are the coverage argument.
#
# cantools is NOT a build dependency. Everything this writes is checked in:
#
#     python3 -m venv /tmp/ct && /tmp/ct/bin/pip install cantools
#     /tmp/ct/bin/python libs/dbc_parser/tests/gen_golden.py
#
# Values are emitted with decode_choices=False, so a signal with a value table
# is compared as a number and the test is not coupled to enumerator naming.

import itertools
import pathlib
import random
import sys

import cantools

HERE = pathlib.Path(__file__).resolve().parent
DBC_DIR = HERE / "dbcs"
GOLDEN_HEADER = HERE / "golden_data.h"

FRAMES_PER_MESSAGE = 48
FRAMES_PER_MUX_GROUP = 16
REJECTION_BUDGET = 400

FRAME_BITS = 64  # every synthetic message is a full 8 byte frame


# --------------------------------------------------------------------------
# Bit layout
# --------------------------------------------------------------------------

def covered_bits(start, length, little_endian):
    """The exact bit indices a signal occupies, or None if it leaves the frame.

    This mirrors the walk the generated decoder performs, including the
    Motorola sawtooth, so a placement accepted here is one the decoder can
    actually index.
    """
    bits = []
    if little_endian:
        for i in range(length):
            bit = start + i
            if bit >= FRAME_BITS:
                return None
            bits.append(bit)
        return bits

    bit = start
    for _ in range(length):
        if bit >= FRAME_BITS or bit < 0:
            return None
        bits.append(bit)
        bit = bit + 15 if bit % 8 == 0 else bit - 1
    return bits


class Frame:
    """Places signals into a frame without overlap."""

    def __init__(self):
        self.used = set()
        self.signals = []

    def place(self, name, length, little_endian, signed, scale, offset, unit=""):
        for start in range(FRAME_BITS):
            bits = covered_bits(start, length, little_endian)
            if bits is None or self.used.intersection(bits):
                continue
            self.used.update(bits)
            self.signals.append({
                "name": name,
                "start": start,
                "length": length,
                "little_endian": little_endian,
                "signed": signed,
                "scale": scale,
                "offset": offset,
                "unit": unit,
            })
            return True
        return False


def field_range(length, signed):
    if signed:
        return -(2 ** (length - 1)), 2 ** (length - 1) - 1
    return 0, 2 ** length - 1


def signal_line(sig, mux=None):
    lo, hi = field_range(sig["length"], sig["signed"])
    # The declared range has to cover every physical value the field can hold,
    # or cantools refuses to encode even with strict=False disabled elsewhere.
    physical = sorted([lo * sig["scale"] + sig["offset"], hi * sig["scale"] + sig["offset"]])
    marker = f" {mux}" if mux else ""
    return (f' SG_ {sig["name"]}{marker} : {sig["start"]}|{sig["length"]}'
            f'@{1 if sig["little_endian"] else 0}{"-" if sig["signed"] else "+"}'
            f' ({sig["scale"]},{sig["offset"]})'
            f' [{physical[0]}|{physical[1]}] "{sig["unit"]}" ECU')


def write_dbc(path, messages, extra_lines=()):
    lines = [
        'VERSION "synthetic -- generated by libs/dbc_parser/tests/gen_golden.py"',
        "",
        "NS_ :",
        "",
        "BS_:",
        "",
        "BU_ : ECU",
        "",
    ]
    for msg in messages:
        lines.append(f'BO_ {msg["id"]} {msg["name"]}: 8 ECU')
        for sig in msg["signals"]:
            lines.append(signal_line(sig, sig.get("mux")))
        lines.append("")
    lines.extend(extra_lines)
    path.write_text("\n".join(lines) + "\n")


# --------------------------------------------------------------------------
# The sweeps
# --------------------------------------------------------------------------

# Lengths chosen to straddle every boundary the bit walk cares about: single
# bit, sub-byte, byte, byte+1, and the 32/53/64 bit points where integer and
# double representations stop agreeing.
LENGTHS = [1, 2, 3, 7, 8, 9, 12, 15, 16, 17, 24, 31, 32, 33, 53, 63, 64]


def build_layout_dbc():
    """Byte order x signedness x length, with identity scaling.

    Isolates the bit walk and sign extension: any failure here is the decoder
    reading the wrong bits, not arithmetic.
    """
    messages = []
    combos = list(itertools.product([True, False], [False, True], LENGTHS))

    frame = Frame()
    index = 0
    placed = 0
    for little, signed, length in combos:
        name = (f'L{length}_{"LE" if little else "BE"}_{"S" if signed else "U"}')
        if not frame.place(name, length, little, signed, 1, 0):
            messages.append({"id": 0x100 + index, "name": f"Layout{index}", "signals": frame.signals})
            index += 1
            frame = Frame()
            if not frame.place(name, length, little, signed, 1, 0):
                continue
        placed += 1

    if frame.signals:
        messages.append({"id": 0x100 + index, "name": f"Layout{index}", "signals": frame.signals})

    return messages, placed, len(combos)


# Scale and offset combinations, chosen so every branch of the generator's type
# selection is exercised: integral vs fractional, positive vs negative, and the
# unsigned-field-with-negative-offset case that used to convert out of range.
SCALINGS = [
    (1, 0),        # identity -> integer type
    (1, -40),      # unsigned field, negative offset -> must become signed
    (1, 100),      # integral positive offset
    (0.1, 0),      # fractional scale -> double
    (0.5, -273.15),  # fractional both
    (-1, 0),       # negative scale -> must become signed
    (-0.25, 10),   # negative fractional scale
    (2, 0),        # integral scale > 1
    (0.001, 0),    # small scale
    (1000, 0),     # large scale
]


def build_scaling_dbc():
    """Scale x offset x signedness, at a couple of fixed widths."""
    messages = []
    frame = Frame()
    index = 0
    placed = 0
    combos = list(itertools.product(SCALINGS, [False, True], [8, 16], [True, False]))

    for (scale, offset), signed, length, little in combos:
        tag = f"S{SCALINGS.index((scale, offset))}"
        name = (f'{tag}_{length}_{"LE" if little else "BE"}_{"S" if signed else "U"}')
        if not frame.place(name, length, little, signed, scale, offset):
            messages.append({"id": 0x200 + index, "name": f"Scaling{index}", "signals": frame.signals})
            index += 1
            frame = Frame()
            if not frame.place(name, length, little, signed, scale, offset):
                continue
        placed += 1

    if frame.signals:
        messages.append({"id": 0x200 + index, "name": f"Scaling{index}", "signals": frame.signals})

    return messages, placed, len(combos)


def build_features_dbc():
    """Multiplexing, value tables, IEEE floats and extended identifiers."""
    messages = []
    extra = []

    # --- multiplexing: four groups, plus a signal outside the multiplex ---
    mux_frame = Frame()
    mux_frame.place("MuxIndex", 4, False, False, 1, 0)
    mux_frame.signals[0]["mux"] = "M"
    mux_frame.place("Always", 8, False, False, 1, 0)
    for group in range(4):
        # Each group gets a differently shaped signal so the gating and the bit
        # walk are exercised together rather than one masking the other.
        length = [8, 16, 12, 3][group]
        little = group % 2 == 0
        signed = group >= 2
        mux_frame.place(f"Group{group}", length, little, signed, 1, 0)
        mux_frame.signals[-1]["mux"] = f"m{group}"
    messages.append({"id": 0x300, "name": "Multiplexed", "signals": mux_frame.signals})

    # --- value tables, including the naming cases that used to break ---
    values_frame = Frame()
    values_frame.place("Plain", 8, True, False, 1, 0)
    values_frame.place("Colliding", 8, True, False, 1, 0)
    values_frame.place("Awkward", 8, True, False, 1, 0)
    messages.append({"id": 0x301, "name": "WithValues", "signals": values_frame.signals})
    extra.extend([
        'VAL_ 769 Plain 0 "Off" 1 "On" 2 "Standby" ;',
        # Two entries that sanitise to the same identifier.
        'VAL_ 769 Colliding 0 "Fault-A" 1 "Fault_A" 2 "Fault A" ;',
        # Leading digit, empty, reserved word, and punctuation only.
        'VAL_ 769 Awkward 0 "0 to 100%" 1 "" 2 "class" 3 "---" ;',
        "",
    ])

    # --- IEEE float and double via SIG_VALTYPE_ ---
    float_frame = Frame()
    float_frame.place("AsFloat", 32, True, True, 1, 0)
    float_frame.place("AsInt", 32, True, False, 1, 0)
    messages.append({"id": 0x302, "name": "FloatSignals", "signals": float_frame.signals})

    double_frame = Frame()
    double_frame.place("AsDouble", 64, True, True, 1, 0)
    messages.append({"id": 0x303, "name": "DoubleSignal", "signals": double_frame.signals})

    extra.extend([
        "SIG_VALTYPE_ 770 AsFloat : 1;",
        "SIG_VALTYPE_ 771 AsDouble : 2;",
        "",
    ])

    # --- extended identifier: bit 31 set is how a DBC spells 29 bit ---
    ext_frame = Frame()
    ext_frame.place("Payload", 32, True, False, 1, 0)
    messages.append({
        "id": 0x80000000 | 0x18FEEE00,
        "name": "ExtendedId",
        "signals": ext_frame.signals,
    })

    # --- comment containing a quote, which must survive into generated code ---
    extra.extend([
        r'CM_ SG_ 769 Plain "a comment with \"quotes\" and a \\ backslash";',
        r'CM_ BO_ 768 "multiplexed message";',
        "",
    ])

    return messages, extra


DATABASES = []


def emit_dbcs():
    DBC_DIR.mkdir(exist_ok=True)

    layout, placed, total = build_layout_dbc()
    write_dbc(DBC_DIR / "dbc_test_layout.dbc", layout)
    print(f"layout:   {len(layout)} messages, {placed}/{total} byte-order x sign x length combos")

    scaling, placed, total = build_scaling_dbc()
    write_dbc(DBC_DIR / "dbc_test_scaling.dbc", scaling)
    print(f"scaling:  {len(scaling)} messages, {placed}/{total} scale x offset x sign x width combos")

    features, extra = build_features_dbc()
    write_dbc(DBC_DIR / "dbc_test_features.dbc", features, extra)
    print(f"features: {len(features)} messages (multiplexing, value tables, floats, extended id)")

    DATABASES.extend([
        ("dbc_test_layout", DBC_DIR / "dbc_test_layout.dbc"),
        ("dbc_test_scaling", DBC_DIR / "dbc_test_scaling.dbc"),
        ("dbc_test_features", DBC_DIR / "dbc_test_features.dbc"),
    ])


# --------------------------------------------------------------------------
# Goldens
# --------------------------------------------------------------------------

def multiplex_groups(message):
    if not message.is_multiplexed():
        return None
    for node in message.signal_tree:
        if isinstance(node, dict):
            name, groups = next(iter(node.items()))
            return name, sorted(groups.keys())
    return None


def fmt(value):
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    return repr(float(value))


def sample_payloads(message, rng):
    groups = multiplex_groups(message)
    if groups is None:
        for _ in range(FRAMES_PER_MESSAGE):
            yield bytes(rng.getrandbits(8) for _ in range(message.length))
        return

    mux_name, group_ids = groups
    wanted = {group_id: FRAMES_PER_MUX_GROUP for group_id in group_ids}
    budget = REJECTION_BUDGET * FRAMES_PER_MUX_GROUP * max(len(group_ids), 1)

    while budget > 0 and any(count > 0 for count in wanted.values()):
        budget -= 1
        payload = bytes(rng.getrandbits(8) for _ in range(message.length))
        try:
            group_id = message.decode(payload, decode_choices=False)[mux_name]
        except Exception:
            continue
        if wanted.get(group_id, 0) <= 0:
            continue
        wanted[group_id] -= 1
        yield payload

    starved = [g for g, count in wanted.items() if count > 0]
    if starved:
        print(f"  warning: {message.name} under-sampled mux groups {starved}", file=sys.stderr)


def emit_database(lib_name, dbc_path):
    db = cantools.database.load_file(dbc_path)

    lines = [f"database {lib_name}"]
    decode_cases = 0
    encode_cases = 0

    for message in db.messages:
        rng = random.Random(message.frame_id)
        lines.append(f"message 0x{message.frame_id:08X} {message.name} {message.length}")

        for payload in sample_payloads(message, rng):
            try:
                decoded = db.decode_message(message.frame_id, payload, decode_choices=False)
            except Exception:
                continue

            lines.append(f"decode {payload.hex()}")
            for name, value in sorted(decoded.items()):
                lines.append(f"  {name} {fmt(value)}")
            decode_cases += 1

            try:
                reencoded = db.encode_message(message.frame_id, decoded, strict=False)
            except Exception:
                continue

            lines.append(f"encode {reencoded.hex()}")
            encode_cases += 1

    print(f"  {lib_name}: {decode_cases} decode, {encode_cases} encode cases")
    return lines, decode_cases, encode_cases


def main():
    emit_dbcs()
    print()

    blocks = []
    total_decode = 0
    total_encode = 0
    for lib_name, dbc_path in DATABASES:
        lines, decodes, encodes = emit_database(lib_name, dbc_path)
        total_decode += decodes
        total_encode += encodes
        body = "\n".join(lines)
        blocks.append(
            f'// {lib_name}\n'
            f'inline constexpr const char* k_{lib_name} = R"GOLDEN(\n{body}\n)GOLDEN";\n'
        )

    header = (
        "#pragma once\n"
        "\n"
        "// Generated by libs/dbc_parser/tests/gen_golden.py -- do not edit.\n"
        "//\n"
        "// cantools' answers for the synthetic DBCs under tests/dbcs/. Embedded\n"
        "// rather than loaded from disk so the test carries its own data and needs\n"
        "// no path handed to it at build time.\n"
        "//\n"
        f"// {total_decode} decode cases, {total_encode} encode cases.\n"
        "\n"
        "namespace golden_data\n"
        "{\n"
        "\n" + "\n".join(blocks) + "\n"
        "}  // namespace golden_data\n"
    )

    GOLDEN_HEADER.write_text(header)
    print(f"\n{GOLDEN_HEADER.name}: {total_decode} decode, {total_encode} encode cases")
    return 0


if __name__ == "__main__":
    sys.exit(main())
