// Differential test: the synthetic DBC sweep, replayed against cantools.
//
// The inputs are generated by gen_golden.py as a systematic sweep over byte
// order x signedness x length x bit alignment x scaling, and the expected
// values are cantools'. A failure means our bit walk, sign extension, scaling
// or multiplex gating disagrees with an independent implementation.
//
// It deliberately does not touch the DBCs under dbcs/. See tests/CMakeLists.txt.

#include "golden_data.h"
#include "golden_replay.h"

#include "dbc_test_features.h"
#include "dbc_test_layout.h"
#include "dbc_test_scaling.h"

#include <cstdio>

namespace
{

// A handful of cases pinned at compile time, so a regression in the bit walk
// is a build failure rather than a test failure. The bulk stays at runtime --
// constant-evaluating thousands of cases would dominate build time for no
// extra coverage.
namespace compile_time
{

using namespace dbc_test_features;

constexpr std::array<uint8_t, 8> kMuxGroup2{0x2A, 0x5C, 0x13, 0x77, 0x91, 0xE0, 0x04, 0xBD};

constexpr int64_t decodedMuxIndex()
{
    Multiplexed_t message;
    message.decode(kMuxGroup2);
    return static_cast<int64_t>(message.MuxIndex);
}

constexpr bool shortFrameRejected()
{
    Multiplexed_t message;
    return !message.decode(std::span<const uint8_t>(kMuxGroup2.data(), 7));
}

// MuxIndex is 4 bits, Motorola, starting at bit 0. The sawtooth walks bit 0,
// then jumps to the top of the next byte: bits 0, 15, 14, 13, most significant
// first. So group 2 (0b0010) puts a single set bit at bit 14, which is bit 6
// of byte 1 -- and nothing at all in byte 0.
constexpr uint8_t encodedByte(size_t index)
{
    Multiplexed_t message;
    message.MuxIndex = 2;
    return message.encode()[index];
}

// decode() and encode() are both usable in a constant expression. encode()
// only became so once the rounding stopped going through std::floor, which is
// not constexpr before C++26.
static_assert(decodedMuxIndex() == 2, "multiplexor should decode to group 2");
static_assert(shortFrameRejected(), "a frame shorter than the message must be rejected");
static_assert(encodedByte(0) == 0x00u, "the multiplexor's high bit lands in byte 0 and is clear");
static_assert(encodedByte(1) == 0x40u, "the rest of the multiplexor lands at bit 6 of byte 1");

// Signal traits are compile-time constants, so the type selection that used to
// hand an unsigned type to a signal with a negative offset is checkable here.
using Coolantish = dbc_test_scaling::Scaling1_t;
static_assert(std::is_same_v<Coolantish::sig_S1_8_LE_U_t::Type, int64_t>,
              "an unsigned field with a negative offset must not decode as unsigned");
static_assert(Coolantish::sig_S1_8_LE_U_t::offset == -40.0);

} // namespace compile_time

} // namespace

int main()
{
    int failures = 0;

    failures += golden::replay<dbc_test_layout::dbc_test_layout_t>(
        "dbc_test_layout", golden_data::k_dbc_test_layout);
    failures += golden::replay<dbc_test_scaling::dbc_test_scaling_t>(
        "dbc_test_scaling", golden_data::k_dbc_test_scaling);
    failures += golden::replay<dbc_test_features::dbc_test_features_t>(
        "dbc_test_features", golden_data::k_dbc_test_features);

    if (failures != 0)
    {
        std::fprintf(stderr, "\n%d disagreement(s) with cantools\n", failures);
        return 1;
    }

    return 0;
}
