#ifndef ZENOH_SERVICE_H_
#define ZENOH_SERVICE_H_

#include <functional>
#include <optional>
#include <string>

#include <zenoh.hxx>
#include "pub_sub/session_manager.h"
#include <capnp/message.h>
#include <capnp/serialize.h>
#include <cstring>

#include "pub_sub/schema_registry.h"
#include "pub_sub/capnp_encoding.h"
#include "pub_sub/capnp_payload.h"
#include "pub_sub/topic_key.h"

#include "spdlog/spdlog.h"

namespace pub_sub
{

// Generic Cap'n Proto-backed queryable service.
// RequestT, ResponseT are Cap'n Proto structs generated by capnp.
// Handler: void(const RequestT::Reader&, ResponseT::Builder&)
template <typename RequestT, typename ResponseT>
class ZenohService
{
  public:
    using RequestReader = typename RequestT::Reader;
    using ResponseBuilder = typename ResponseT::Builder;
    using Handler = std::function<void(const RequestReader&, ResponseBuilder&)>;

    ZenohService(std::string keyexpr, Handler handler) :
        mKeyExpr(std::move(keyexpr)),
        mHandler(std::move(handler)),
        mSession(pub_sub::SessionManager::getOrCreate())
    {
        
        auto on_query = [this](const zenoh::Query& query)
        {
            // Decode request (if any)
            capnp::MallocMessageBuilder respBuilder;
            auto resp = respBuilder.template initRoot<ResponseT>();

            if (auto payloadRef = query.get_payload())
            {
                const auto& bytes = payloadRef->get();
                auto v = bytes.as_vector();
                const WordAlignedPayload aligned(v);
                if (!aligned.empty())
                {
                    capnp::FlatArrayMessageReader reader(aligned.words());
                    auto req = reader.template getRoot<RequestT>();
                    SPDLOG_DEBUG("Received request for key '{}' = {}", mKeyExpr, req.toString().flatten().cStr());
                    mHandler(req, resp);
                }
                else
                {
                    // Payload malformed; handler not invoked. Respond with default-constructed response.
                    SPDLOG_ERROR("Payload malformed for key '{}'", mKeyExpr);
                }
            }
            else
            {
                SPDLOG_ERROR("No payload for key '{}'", mKeyExpr);
            }

            SPDLOG_DEBUG("Sending response to key '{}' = {}", mKeyExpr, resp.toString().flatten().cStr());

            // Serialize and reply.
            //
            // capnp has already laid the message out contiguously; zenoh is
            // handed THAT buffer rather than a copy of it. This used to
            // allocate a second buffer the size of the whole reply and memcpy
            // into it, which for a map tile is a hundred kilobytes moved to
            // produce bytes identical to the ones next to it -- on every
            // request, for every service on the bus.
            //
            // The kj::Array is moved onto the heap and released by the
            // deleter, which zenoh calls once the payload and every clone of
            // it are done. Nothing here may assume the reply has been sent by
            // the time reply() returns.
            auto* held = new kj::Array<capnp::word>(capnp::messageToFlatArray(respBuilder));
            const std::size_t bytes = held->size() * sizeof(capnp::word);

            zenoh::Query::ReplyOptions ropts = zenoh::Query::ReplyOptions::create_default();
            ropts.encoding.emplace(kCapnpEncodingMime);
            ropts.encoding->set_schema(std::string(schema_traits<ResponseT>::name));
            query.reply(mKeyExpr,
                        zenoh::Bytes(reinterpret_cast<uint8_t*>(held->begin()), bytes,
                                     [held](uint8_t*) { delete held; }),
                        std::move(ropts));
        };

        auto on_drop = []() {};

        mQueryable = mSession->declare_queryable(
            zenoh::KeyExpr(mKeyExpr),
            on_query,
            on_drop,
            zenoh::Session::QueryableOptions::create_default()
        );

        SPDLOG_DEBUG("Service active on '{}' for schemas '{}'->'{}'", mKeyExpr, schema_traits<RequestT>::name, schema_traits<ResponseT>::name);

        // Announce the service, for the same reason a publisher announces its
        // topic: a queryable is otherwise undiscoverable. Zenoh will route a
        // request to it, but nothing on the bus says it exists, what key to send
        // to, or what a request should contain -- you had to read the source of
        // whichever node offers it. The two schema names are exactly what a
        // caller needs, and they are already available here as template
        // parameters.
        //
        // Declared after the queryable, so a token never names a service that
        // cannot answer.
        try
        {
            const std::string advertised = serviceKey(
                mKeyExpr, schema_traits<RequestT>::name, schema_traits<ResponseT>::name,
                mSession->get_zid().to_string());
            mAdvertisement.emplace(
                mSession->liveliness_declare_token(zenoh::KeyExpr(advertised)));
            SPDLOG_DEBUG("Advertised service '{}' as '{}'", mKeyExpr, advertised);
        }
        catch (const std::exception& e)
        {
            // Not fatal: an unannounced service still answers anyone who knows
            // its key, which is every caller that exists today.
            SPDLOG_WARN("Service on '{}' is running but could not be advertised: {}", mKeyExpr,
                        e.what());
        }
    }

    ~ZenohService()
    {
        if (mQueryable.has_value())
        {
            std::move(mQueryable.value()).undeclare();
            mQueryable.reset();
        }
    }

    ZenohService(const ZenohService&) = delete;
    ZenohService& operator=(const ZenohService&) = delete;
    ZenohService(ZenohService&&) noexcept = default;
    ZenohService& operator=(ZenohService&&) noexcept = delete;

private:
    std::string mKeyExpr;
    Handler mHandler;
    std::optional<zenoh::Queryable<void>> mQueryable;
    std::shared_ptr<zenoh::Session> mSession;

    // The liveliness token that makes this service discoverable. See the
    // constructor; empty when it could not be declared, which is not fatal.
    std::optional<zenoh::LivelinessToken> mAdvertisement;
};

} // namespace pub_sub

#endif // ZENOH_SERVICE_H_


