#ifndef ZENOH_SERVICE_H_
#define ZENOH_SERVICE_H_

#include <functional>
#include <optional>
#include <string>

#include <zenoh.hxx>
#include "pub_sub/session_manager.h"
#include <capnp/message.h>
#include <capnp/serialize.h>
#include <cstring>

#include "pub_sub/schema_registry.h"
#include "pub_sub/capnp_encoding.h"

#include "spdlog/spdlog.h"

namespace pub_sub
{

// Generic Cap'n Proto-backed queryable service.
// RequestT, ResponseT are Cap'n Proto structs generated by capnp.
// Handler: void(const RequestT::Reader&, ResponseT::Builder&)
template <typename RequestT, typename ResponseT>
class ZenohService
{
  public:
    using RequestReader = typename RequestT::Reader;
    using ResponseBuilder = typename ResponseT::Builder;
    using Handler = std::function<void(const RequestReader&, ResponseBuilder&)>;

    ZenohService(std::string keyexpr, Handler handler) :
        mKeyExpr(std::move(keyexpr)),
        mHandler(std::move(handler)),
        mSession(pub_sub::SessionManager::getOrCreate())
    {
        
        auto on_query = [this](const zenoh::Query& query)
        {
            // Decode request (if any)
            capnp::MallocMessageBuilder respBuilder;
            auto resp = respBuilder.template initRoot<ResponseT>();

            if (auto payloadRef = query.get_payload())
            {
                const auto& bytes = payloadRef->get();
                auto v = bytes.as_vector();
                if (v.size() % sizeof(capnp::word) == 0)
                {
                    auto words = kj::arrayPtr(reinterpret_cast<const capnp::word*>(v.data()), v.size() / sizeof(capnp::word));
                    capnp::FlatArrayMessageReader reader(words);
                    auto req = reader.template getRoot<RequestT>();
                    SPDLOG_DEBUG("Received request for key '{}' = {}", mKeyExpr, req.toString().flatten().cStr());
                    mHandler(req, resp);
                }
                else
                {
                    // Payload malformed; handler not invoked. Respond with default-constructed response.
                    SPDLOG_ERROR("Payload malformed for key '{}'", mKeyExpr);
                }
            }
            else
            {
                SPDLOG_ERROR("No payload for key '{}'", mKeyExpr);
            }

            SPDLOG_DEBUG("Sending response to key '{}' = {}", mKeyExpr, resp.toString().flatten().cStr());

            // Serialize and reply
            kj::Array<capnp::word> respWords = capnp::messageToFlatArray(respBuilder);
            kj::ArrayPtr<const kj::byte> respBytesView = respWords.asBytes();
            std::vector<uint8_t> respBytes(respBytesView.size());
            std::memcpy(respBytes.data(), respBytesView.begin(), respBytesView.size());

            zenoh::Query::ReplyOptions ropts = zenoh::Query::ReplyOptions::create_default();
            ropts.encoding.emplace(kCapnpEncodingMime);
            ropts.encoding->set_schema(std::string(schema_traits<ResponseT>::name));
            query.reply(mKeyExpr, zenoh::Bytes(std::move(respBytes)), std::move(ropts));
        };

        auto on_drop = []() {};

        mQueryable = mSession->declare_queryable(
            zenoh::KeyExpr(mKeyExpr),
            on_query,
            on_drop,
            zenoh::Session::QueryableOptions::create_default()
        );

        SPDLOG_DEBUG("Service active on '{}' for schemas '{}'->'{}'", mKeyExpr, schema_traits<RequestT>::name, schema_traits<ResponseT>::name);
    }

    ~ZenohService()
    {
        if (mQueryable.has_value())
        {
            std::move(mQueryable.value()).undeclare();
            mQueryable.reset();
        }
    }

    ZenohService(const ZenohService&) = delete;
    ZenohService& operator=(const ZenohService&) = delete;
    ZenohService(ZenohService&&) noexcept = default;
    ZenohService& operator=(ZenohService&&) noexcept = delete;

private:
    std::string mKeyExpr;
    Handler mHandler;
    std::optional<zenoh::Queryable<void>> mQueryable;
    std::shared_ptr<zenoh::Session> mSession;
};

// The other half: calling one of the services above.
//
// `build` fills in the request, and the reply is handed to `consume`. Returns
// false when nobody answered within the timeout -- which for a service is the
// normal way to discover the node providing it is not running, since zenoh has
// no registry to ask.
//
// Blocking, and meant for a one-shot: a command-line tool changing a setting,
// a test driving a node. Something that needs to call a service continuously
// wants its own session and channel rather than one per call.
template <typename RequestT, typename ResponseT, typename BuildFn, typename ConsumeFn>
bool call_service(const std::string& keyexpr, BuildFn&& build, ConsumeFn&& consume,
                  uint64_t timeout_ms = 2000)
{
    auto session = pub_sub::SessionManager::getOrCreate();
    if (!session)
    {
        SPDLOG_ERROR("No zenoh session available to call '{}'", keyexpr);
        return false;
    }

    capnp::MallocMessageBuilder requestBuilder;
    auto request = requestBuilder.template initRoot<RequestT>();
    build(request);

    kj::Array<capnp::word> words = capnp::messageToFlatArray(requestBuilder);
    kj::ArrayPtr<const kj::byte> view = words.asBytes();
    std::vector<uint8_t> payload(view.size());
    std::memcpy(payload.data(), view.begin(), view.size());

    auto options = zenoh::Session::GetOptions::create_default();
    options.payload = zenoh::Bytes(std::move(payload));
    options.timeout_ms = timeout_ms;

    // A one-reply channel: these services have exactly one provider, and a
    // second answer would mean two nodes are claiming the same key.
    auto replies = session->get(zenoh::KeyExpr(keyexpr), "", zenoh::channels::FifoChannel(1),
                                std::move(options));

    for (auto reply = replies.recv(); std::holds_alternative<zenoh::Reply>(reply);
         reply = replies.recv())
    {
        const auto& value = std::get<zenoh::Reply>(reply);
        if (!value.is_ok())
        {
            SPDLOG_ERROR("Service '{}' returned an error", keyexpr);
            return false;
        }

        const auto bytes = value.get_ok().get_payload().as_vector();
        if (bytes.size() % sizeof(capnp::word) != 0)
        {
            SPDLOG_ERROR("Service '{}' replied with a misaligned payload of {} bytes", keyexpr,
                         bytes.size());
            return false;
        }

        auto replyWords = kj::arrayPtr(reinterpret_cast<const capnp::word*>(bytes.data()),
                                       bytes.size() / sizeof(capnp::word));
        capnp::FlatArrayMessageReader reader(replyWords);
        consume(reader.template getRoot<ResponseT>());
        return true;
    }

    SPDLOG_ERROR("No reply from '{}' within {} ms -- is the node providing it running?", keyexpr,
                 timeout_ms);
    return false;
}

} // namespace pub_sub

#endif // ZENOH_SERVICE_H_


