title: Digital Dashboard
description: Instrument cluster widgets, CarPlay, and more.
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock


