#include "expression_parser/schema_registry.h"

// Include all known schemas to get their IDs
#include "vehicle_warnings.capnp.h"
#include "engine_rpm.capnp.h"
#include "engine_temperature.capnp.h"
#include "vehicle_speed.capnp.h"

// This gets generated by the CMake script.
// A static array of schema names.
constexpr available_schemas_t kAvailableSchemas =
{
@SCHEMA_STATIC_ARRAY@
};

capnp::Schema get_schema_by_name(const std::string& schema_name)
{
// This gets generated by the CMake script.
// A bunch of if statements to compare the schema name string to return the correct schema.
@SCHEMA_CONDITIONAL_LOGIC@

    return {};
}
