#include "expression_parser/schema_registry.h"

// Include all known schemas to get their IDs.  This gets populated by the CMake script.
@SCHEMA_INCLUDES@

// This gets generated by the CMake script.
// A static array of schema names.
constexpr available_schemas_t kAvailableSchemas =
{
@SCHEMA_STATIC_ARRAY@
};

capnp::Schema get_schema(const std::string_view& schema_name)
{
// This gets generated by the CMake script.
// A bunch of if statements to compare the schema name string to return the correct schema.
@SCHEMA_CONDITIONAL_LOGIC@

    return {};
}

capnp::Schema get_schema(schema_type_t schema_type)
{
// This gets generated by the CMake script.
// A bunch of if statements to compare the schema type to return the correct schema.
@SCHEMA_CONDITIONAL_LOGIC_BY_TYPE@

    return {};
}
